In [43]:

from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [44]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [45]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [46]:
## Define the vocabulary size

voc_size = 10000
sent_length = 500


In [47]:
from tensorflow.keras.preprocessing.text import one_hot

onehot_repr = [one_hot(words, voc_size) for words in sent]

In [48]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)

In [49]:
print(embedded_docs.shape)

(7, 500)


In [50]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [51]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr


[[9440, 4420, 418, 2712],
 [9440, 4420, 418, 7857],
 [9440, 7897, 418, 3618],
 [4910, 5210, 1543, 8168, 7601],
 [4910, 5210, 1543, 8168, 4269],
 [3482, 9440, 319, 418, 189],
 [1568, 7712, 1470, 8168]]

In [52]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [53]:
import numpy as np

In [54]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9440 4420  418 2712]
 [   0    0    0    0 9440 4420  418 7857]
 [   0    0    0    0 9440 7897  418 3618]
 [   0    0    0 4910 5210 1543 8168 7601]
 [   0    0    0 4910 5210 1543 8168 4269]
 [   0    0    0 3482 9440  319  418  189]
 [   0    0    0    0 1568 7712 1470 8168]]


In [55]:
## feature representation
dim=10

In [66]:
voc_size = 10000
dim = 10


In [68]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

In [69]:
vocab_size = 10000

In [70]:
model = Sequential()

model.add(Embedding(input_dim=vocab_size, output_dim=128, input_length=8))

model.add(SimpleRNN(128, return_sequences=False))

model.add(Dense(1, activation='sigmoid'))

In [71]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [74]:
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence

vocab_size = 10000
maxlen = 8

(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=vocab_size)

In [75]:
X_train = sequence.pad_sequences(X_train, maxlen=maxlen)
X_test = sequence.pad_sequences(X_test, maxlen=maxlen)

In [76]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=5)

Epoch 1/5


782/782 [==============================] - 25s 30ms/step - loss: 0.5821 - accuracy: 0.6792 - val_loss: 0.5467 - val_accuracy: 0.7144
Epoch 2/5
782/782 [==============================] - 23s 29ms/step - loss: 0.4560 - accuracy: 0.7828 - val_loss: 0.5822 - val_accuracy: 0.7071
Epoch 3/5
782/782 [==============================] - 25s 32ms/step - loss: 0.3410 - accuracy: 0.8506 - val_loss: 0.6563 - val_accuracy: 0.6805
Epoch 4/5
782/782 [==============================] - 26s 33ms/step - loss: 0.2565 - accuracy: 0.8945 - val_loss: 0.7492 - val_accuracy: 0.6818
Epoch 5/5
782/782 [==============================] - 26s 33ms/step - loss: 0.2080 - accuracy: 0.9162 - val_loss: 0.8462 - val_accuracy: 0.6803


In [77]:
model.save("model.keras")

In [78]:
sample = X_test[0].reshape(1, -1)
prediction = model.predict(sample)

print(prediction)

1/1 [==============================] - 0s 175ms/step
[[0.71272063]]


In [58]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [59]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [60]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 74ms/step


array([[[ 4.80030663e-02, -2.95633562e-02,  2.68996842e-02,
          7.51819462e-03, -3.10649630e-02,  2.42121480e-02,
          3.20010073e-02,  1.88515447e-02,  3.75548750e-03,
         -9.18873399e-03],
        [ 4.80030663e-02, -2.95633562e-02,  2.68996842e-02,
          7.51819462e-03, -3.10649630e-02,  2.42121480e-02,
          3.20010073e-02,  1.88515447e-02,  3.75548750e-03,
         -9.18873399e-03],
        [ 4.80030663e-02, -2.95633562e-02,  2.68996842e-02,
          7.51819462e-03, -3.10649630e-02,  2.42121480e-02,
          3.20010073e-02,  1.88515447e-02,  3.75548750e-03,
         -9.18873399e-03],
        [ 4.80030663e-02, -2.95633562e-02,  2.68996842e-02,
          7.51819462e-03, -3.10649630e-02,  2.42121480e-02,
          3.20010073e-02,  1.88515447e-02,  3.75548750e-03,
         -9.18873399e-03],
        [ 2.62648799e-02,  1.15803964e-02,  2.92814709e-02,
          1.45450570e-02, -3.10650356e-02,  4.28634323e-02,
          9.16818529e-03,  4.41205613e-02, -1.111502

In [61]:
embedded_docs[0]

array([   0,    0,    0,    0, 9440, 4420,  418, 2712])

In [62]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 52ms/step


array([[ 0.04800307, -0.02956336,  0.02689968,  0.00751819, -0.03106496,
         0.02421215,  0.03200101,  0.01885154,  0.00375549, -0.00918873],
       [ 0.04800307, -0.02956336,  0.02689968,  0.00751819, -0.03106496,
         0.02421215,  0.03200101,  0.01885154,  0.00375549, -0.00918873],
       [ 0.04800307, -0.02956336,  0.02689968,  0.00751819, -0.03106496,
         0.02421215,  0.03200101,  0.01885154,  0.00375549, -0.00918873],
       [ 0.04800307, -0.02956336,  0.02689968,  0.00751819, -0.03106496,
         0.02421215,  0.03200101,  0.01885154,  0.00375549, -0.00918873],
       [ 0.02626488,  0.0115804 ,  0.02928147,  0.01454506, -0.03106504,
         0.04286343,  0.00916819,  0.04412056, -0.01111503, -0.00530415],
       [ 0.03687104,  0.01632544, -0.03204261, -0.04692559,  0.0014407 ,
         0.01151752, -0.0065813 ,  0.03454124, -0.01196945,  0.04911746],
       [ 0.00260561, -0.00380076,  0.00540968, -0.01350629,  0.00616433,
        -0.02872356,  0.00254873, -0.02079527

In [63]:
import numpy as np

model.predict(np.array([embedded_docs[0]]))

1/1 [==============================] - 0s 47ms/step


array([[[ 0.04800307, -0.02956336,  0.02689968,  0.00751819,
         -0.03106496,  0.02421215,  0.03200101,  0.01885154,
          0.00375549, -0.00918873],
        [ 0.04800307, -0.02956336,  0.02689968,  0.00751819,
         -0.03106496,  0.02421215,  0.03200101,  0.01885154,
          0.00375549, -0.00918873],
        [ 0.04800307, -0.02956336,  0.02689968,  0.00751819,
         -0.03106496,  0.02421215,  0.03200101,  0.01885154,
          0.00375549, -0.00918873],
        [ 0.04800307, -0.02956336,  0.02689968,  0.00751819,
         -0.03106496,  0.02421215,  0.03200101,  0.01885154,
          0.00375549, -0.00918873],
        [ 0.02626488,  0.0115804 ,  0.02928147,  0.01454506,
         -0.03106504,  0.04286343,  0.00916819,  0.04412056,
         -0.01111503, -0.00530415],
        [ 0.03687104,  0.01632544, -0.03204261, -0.04692559,
          0.0014407 ,  0.01151752, -0.0065813 ,  0.03454124,
         -0.01196945,  0.04911746],
        [ 0.00260561, -0.00380076,  0.00540968, -0.0

In [64]:
model.save("simple_rnn_imdb.keras")